### ISSUE TITLE
Update to current version

### ISSUE THREAD

**Issue by diamanat** [ilpozzd/terraform-talos-vm-userdata#3]
Hi! Why did you abandon it? This is a really cool project. Maybe there are some options to update for new versions of Talos

**Comment by ilvpozzd** [comment]
> Hi! Why did you abandon it? This is a really cool project. Maybe there are some options to update for new versions of Talos

Hello! Keeping the module up-to-date is no longer in demand, since Talos now has its own terraform provider, which can also be used to create configurations. See https://registry.terraform.io/providers/siderolabs/talos/latest/docs
